name: Manual workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Autoupdate
        uses: siarheidudko/autoupdater@v1
        with:
          branch: 'dev'
